services:
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - JAVA_HELLO
      - POSTGRES_DB
      - POSTGRES_PASSWORD
  db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    expose:
      - 5432
