services:
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_DB=todos
      - POSTGRES_PASSWORD=Password1!
    expose:
      - 5432
